import {useState} from 'react';
import {Bell,Building2,CheckSquare,ChevronRight,FolderKanban,LayoutDashboard,Settings,Users,Wallet,BarChart3,Phone,MessageCircle,Plus,Search,CalendarClock} from 'lucide-react';

const menu=[[LayoutDashboard,'Главная'],[Users,'CRM'],[FolderKanban,'Проекты'],[CheckSquare,'Задачи'],[Building2,'Клиенты'],[Wallet,'Финансы'],[BarChart3,'Аналитика'],[Settings,'Настройки']] as const;
const deals=[
 {id:1,name:'АН «Квадрат»',contact:'Мария',amount:'65 000 ₽',source:'2ГИС',follow:'Сегодня, 18:00',stage:'Новый лид'},
 {id:2,name:'Недвижимость 56',contact:'Алексей',amount:'45 000 ₽',source:'WhatsApp',follow:'Завтра, 10:00',stage:'Новый лид'},
 {id:3,name:'Дом Ипотек',contact:'Сергей',amount:'80 000 ₽',source:'Рекомендация',follow:'Просрочено',stage:'Контакт'},
 {id:4,name:'АН «Мегаполис»',contact:'Ольга',amount:'55 000 ₽',source:'Сайт',follow:'25 сен, 12:00',stage:'Контакт'},
 {id:5,name:'Ключ',contact:'Ирина',amount:'70 000 ₽',source:'2ГИС',follow:'26 сен, 15:00',stage:'КП отправлено'},
 {id:6,name:'Этажи — партнёр',contact:'Дмитрий',amount:'95 000 ₽',source:'Холодный',follow:'Сегодня, 20:00',stage:'Переговоры'}
];
const columns=['Новый лид','Контакт','КП отправлено','Переговоры'];
const attention=[{name:'АН «Квадрат»',task:'Отправить коммерческое предложение',time:'Сегодня, 18:00',kind:'message'},{name:'Дом Ипотек',task:'Позвонить по заявке',time:'Просрочено на 1 день',kind:'phone'},{name:'Новый лид',task:'Ответить в WhatsApp',time:'Сегодня, 20:30',kind:'message'}];
const tasks=[['Подготовить прототип лендинга','Высокий'],['Связаться с 10 агентствами недвижимости','Высокий'],['Проверить рекламную кампанию','Средний']];
function Metric({label,value,note}:{label:string,value:string,note:string}){return <div className="card metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

export default function App(){
 const [page,setPage]=useState('Главная');
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark">S</div><div><b>StudioFlow</b><span>Web Studio OS</span></div></div><nav>{menu.map(([Icon,label])=><button onClick={()=>setPage(label)} className={page===label?'active':''} key={label}><Icon size={19}/><span>{label}</span>{label==='CRM'&&<em>12</em>}</button>)}</nav><div className="profile"><div className="avatar">АК</div><div><b>Айнур</b><span>Администратор</span></div><ChevronRight size={17}/></div></aside>
 <main>{page==='CRM'?<CRM/>:<Dashboard openCRM={()=>setPage('CRM')}/>}</main></div>
}
function Top({title,subtitle}:{title:string,subtitle:string}){return <header><div><h1>{title}</h1><p>{subtitle}</p></div><div className="headerActions"><button className="icon"><Bell size={19}/><i/></button><button className="primary"><Plus size={18}/>Новая сделка</button></div></header>}
function Dashboard({openCRM}:{openCRM:()=>void}){return <><Top title="Главная" subtitle="Контроль продаж и работы студии"/><section className="metrics"><Metric label="Новые лиды" value="34" note="+8 за неделю"/><Metric label="Активные сделки" value="12" note="На 486 000 ₽"/><Metric label="Продажи" value="186 000 ₽" note="+24% к прошлому месяцу"/><Metric label="Проекты в работе" value="7" note="2 требуют внимания"/></section><div className="grid"><section className="card panel"><div className="panelHead"><div><h2>Требуют внимания</h2><p>Follow-up на сегодня</p></div><button onClick={openCRM}>Все контакты <ChevronRight size={16}/></button></div>{attention.map((x,i)=><div className="row" key={x.name}><div className={'activity '+(i===1?'danger':'')}>{x.kind==='phone'?<Phone size={17}/>:<MessageCircle size={17}/>}</div><div className="grow"><b>{x.name}</b><span>{x.task}</span></div><time className={i===1?'overdue':''}>{x.time}</time></div>)}</section><section className="card panel"><div className="panelHead"><div><h2>Задачи на сегодня</h2><p>3 задачи · 0 выполнено</p></div></div>{tasks.map(([task,priority],i)=><label className="task" key={task}><input type="checkbox"/><div className="grow"><b>{task}</b><span>StudioFlow · сегодня</span></div><em className={i===2?'medium':''}>{priority}</em></label>)}</section></div><section className="card pipeline"><div className="panelHead"><div><h2>Воронка продаж</h2><p>Текущий месяц</p></div><button onClick={openCRM}>Открыть CRM <ChevronRight size={16}/></button></div><div className="stages">{[['Новый лид','18','540 000 ₽'],['Контакт','11','330 000 ₽'],['КП отправлено','7','245 000 ₽'],['Переговоры','4','180 000 ₽'],['Успешно','3','186 000 ₽']].map((s,i)=><div className="stage" key={s[0]}><div className="stageTop"><span>{s[0]}</span><b>{s[1]}</b></div><strong>{s[2]}</strong><div className="bar"><i style={{width:`${100-i*17}%`}}/></div></div>)}</div></section></>}
function CRM(){return <><Top title="CRM · Сделки" subtitle="Управление продажами и следующими контактами"/><div className="crmTools"><div className="search"><Search size={17}/><input placeholder="Поиск по сделкам и клиентам"/></div><button className="filter"><CalendarClock size={17}/> Follow-up сегодня <b>3</b></button></div><div className="kanban">{columns.map(col=>{const list=deals.filter(d=>d.stage===col);return <section className="kanbanCol" key={col}><div className="colHead"><div><span className="dot"/><b>{col}</b><em>{list.length}</em></div><strong>{list.reduce((s,d)=>s+parseInt(d.amount.replace(/\D/g,'')),0).toLocaleString('ru-RU')} ₽</strong></div><div className="dealList">{list.map(d=><article className="deal card" key={d.id}><div className="dealTop"><small>{d.source}</small><button>•••</button></div><h3>{d.name}</h3><p>{d.contact}</p><strong>{d.amount}</strong><div className={'follow '+(d.follow==='Просрочено'?'late':'')}><CalendarClock size={14}/><span>{d.follow}</span></div></article>)}</div><button className="addDeal"><Plus size={15}/> Добавить сделку</button></section>})}</div></>}
